nelmio_api_doc:
    documentation:
        info:
            title: 'EcoRide API' 
            description: 'L''API officielle pour la plateforme de covoiturage EcoRide.' 
            version: 1.0.0
        servers:
            - url: '%env(APP_URL)%'
              description: 'Serveur de production Heroku'
    
   
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Scanne toutes les routes sous /api

    # Ligne de sécurité pour éviter les conflits avec d'autres bundles
    models: { use_jms: false }

