nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        servers:
            - url: '%env(APP_URL)%'
              description: Production server
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$) # Documente toutes les routes sous /api sauf /api/doc
