security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path : ^/api/doc, roles : PUBLIC_ACCESS }
        - { path: ^/api/covoiturage/search, roles: PUBLIC_ACCESS}
        - { path: ^/api/covoiturage/details/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/api/covoiturage/filter, roles: PUBLIC_ACCESS}
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/profile/status, roles: IS_AUTHENTICATED_FULLY}
  
