# Exposez votre documentation au format JSON compatible Swagger
app.swagger:
    path: /api/doc.json
    methods: [GET]
    controller: nelmio_api_doc.controller.swagger

# Nécessite le composant Asset et le bundle Twig
# Commande à exécuter : composer require twig asset
app.swagger_ui:
    path: /api/doc
    methods: [GET]
    controller: nelmio_api_doc.controller.swagger_ui
