services:
  mysql:
    type: "mysql:8.0"  # Choisir la version de MySQL
    disk: 1024         # Ajuster la taille du disque si nécessaire

  mongodb:
    type: "mongodb:4.4"  # Version MongoDB
    disk: 1024           # Taille du disque pour MongoDB
